#!/bin/bash

pushd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null

find ./data/gtfs/ \
    -mindepth 1 \
    -type d \
    -printf '%f\n' |
  sort |
  while read -r agency; do
    ./do_conflation_for_agency "$agency"
  done

./bin/combine_way_trip_counts > ./gtfs_osm_conflation/combined_way_trip_counts.csv

popd >/dev/null
